import assert from 'node:assert/strict';
import { readFile, writeFile, mkdtemp, mkdir } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { once } from 'node:events';
import { resolve } from 'node:path';
import { expect } from '@playwright/test';
import { Client, StreamableHTTPClientTransport } from '@modelcontextprotocol/client';
import { nativeHarness } from './native-harness.mjs';
import { waitForService } from './service-ready.mjs';
import { decodeDocument } from '../src/document-state.js';
import { unzipSync } from 'fflate';

await mkdir('.runtime', { recursive: true });
const allocator = createServer(); allocator.listen(0, '127.0.0.1'); await once(allocator, 'listening');
const port = allocator.address().port; await new Promise(r => allocator.close(r));
const storage = await mkdtemp(resolve('.runtime/annotations-qa-')), origin = `http://127.0.0.1:${port}`;
const service = spawn(process.execPath, ['server/index.mjs'], { windowsHide: true, env: { ...process.env, CANVY_PORT: String(port), CANVY_DATA_DIR: storage }, stdio: 'ignore' });
const client = new Client({ name: 'annotations-qa', version: '1' }); let host;
const checks = [];
const call = async (name, args = {}) => { const result = await client.callTool({ name, arguments: args }, { timeout: 120000 }); assert.ok(!result.isError, `${name}: ${JSON.stringify(result.content)}`); return result.structuredContent ?? JSON.parse(result.content[0].text); };
try {
  await waitForService(origin, service);
  await client.connect(new StreamableHTTPClientTransport(new URL(origin + '/mcp')));
  const document = (await call('create_canvas', { name: 'Annotation QA' })).document, target = { document_id: document.id };
  host = await nativeHarness(client, origin, undefined, { nonceCsp: true });
  host.page.setDefaultTimeout(20000);
  const panel = await host.addPanel(document.id);
  const imported = await call('canvas_import_react', { ...target, name: 'Annotation fixture', viewports: [{ width: 600, height: 500 }], source: `import React from 'react';export default function Screen(){const [open,setOpen]=React.useState(false);const [count,setCount]=React.useState(0);return <main style={{padding:40,fontFamily:'Inter'}}><button id="menu" onClick={()=>setOpen(!open)}>Menu</button><p>Count: {count}</p>{open&&<div style={{padding:30,border:'1px solid #aaa'}}><button id="export-item" onClick={()=>setCount(count+1)}>Export CSV</button></div>}</main>}` });
  const frameId = imported.frames[0].id, inline = panel.surface.locator('.inline-prototype').first();
  await expect(inline).toHaveAttribute('data-ready', 'true');
  const prototype = panel.surface.frameLocator('.inline-prototype iframe');
  await prototype.getByRole('button', { name: 'Menu', exact: true }).click();
  const item = prototype.getByRole('button', { name: 'Export CSV' });
  await expect(item).toBeVisible();
  const bounds = await item.boundingBox();
  const checkpointPath = resolve(storage, 'canvases', document.id + '.freecanvas');
  const before = decodeDocument(await readFile(checkpointPath, 'utf8'));
  const backup = await readFile(resolve(storage, 'canvases', document.id + '.fig'));
  await panel.surface.getByRole('button', { name: 'Annotate', exact: true }).click();
  await host.page.mouse.click(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  const comment = panel.surface.getByRole('textbox', { name: 'Annotation comment' });
  await expect(comment).toBeVisible();
  await comment.fill('Millora aquest menú — preserve my words.');
  await expect(panel.surface.locator('main')).toHaveAttribute('data-saved', 'true', { timeout: 20000 });
  let graph = decodeDocument(await readFile(checkpointPath, 'utf8'));
  const note = graph.canvyResources.annotations[0];
  assert.equal(note.target.source, 'live-prototype'); assert.equal(note.target.selector, '#export-item');
  assert.equal(note.target.anchor_id, frameId); assert.equal(note.text, 'Millora aquest menú — preserve my words.');
  assert.deepEqual([...graph.nodes], [...before.nodes]);
  // Archive timestamps and meta.createdAt change; the design payload must not.
  const designPayload = bytes => {
    const entries = unzipSync(bytes); delete entries['meta.json']; return entries;
  };
  assert.deepEqual(designPayload(await readFile(resolve(storage, 'canvases', document.id + '.fig'))), designPayload(backup));
  checks.push('Live DOM picking captures the open menu selector without clicking the mockup or mutating native nodes; comment text and original backup are preserved');
  await panel.surface.getByRole('button', { name: 'Dictate in Codex', exact: true }).click();
  await expect(panel.surface.getByText('Target ready in chat.', { exact: false })).toBeVisible();
  assert.equal(await host.page.evaluate(() => window.nativeMessages.length), 0);
  const context = await host.page.evaluate(() => window.nativeContexts.at(-1).structuredContent);
  assert.equal(context.document_id, document.id); assert.equal(context.active_annotation.id, note.id);
  checks.push('Dictation handoff only updates target context; no microphone substitute, message or forced composer draft');
  await call('canvas_set_annotation', { ...target, annotation_id: note.id, text: 'Feedback from the actual chat dictation', expected_updated_at: note.updated_at });
  await expect(comment).toHaveValue('Feedback from the actual chat dictation');
  const conflict = await client.callTool({ name: 'canvas_set_annotation', arguments: { ...target, annotation_id: note.id, text: 'Stale edit', expected_updated_at: note.updated_at } });
  assert.ok(conflict.isError); assert.match(conflict.content[0].text, /changed since/);
  assert.equal(decodeDocument(await readFile(checkpointPath, 'utf8')).canvyResources.annotations[0].text, 'Feedback from the actual chat dictation');
  checks.push('Agents can persist dictated comments by annotation ID with an acknowledged save; stale feedback writes cannot overwrite human edits');
  await panel.surface.getByRole('button', { name: 'Send annotation to Codex' }).click();
  await expect(panel.surface.getByText('Annotation sent to Codex', { exact: true })).toBeVisible();
  const message = await host.page.evaluate(() => window.nativeMessages[0]);
  assert.ok(message.content[0].text.includes(note.id)); assert.ok(message.content[0].text.includes('#export-item'));
  await host.page.evaluate(() => { window.rejectMessages = true; });
  await panel.surface.getByRole('button', { name: 'Send annotation to Codex' }).click();
  await expect(panel.surface.getByText('Delivery could not be confirmed.', { exact: false })).toBeVisible();
  await expect(panel.surface.getByRole('button', { name: 'Send annotation to Codex' })).toBeDisabled();
  assert.equal(await host.page.evaluate(() => window.nativeMessages.length), 2);
  checks.push('Explicit send carries feedback identity and selector; uncertain/rejected sends retain the comment and are not replayed');
  await panel.surface.getByRole('button', { name: 'Close annotation' }).click();
  const canvasBox = await panel.surface.getByTestId('design-canvas').boundingBox();
  const frameBox = await inline.boundingBox();
  const start = { x: frameBox.x + frameBox.width * .4, y: frameBox.y + frameBox.height * .6 };
  await host.page.mouse.move(start.x, start.y); await host.page.mouse.down(); await host.page.mouse.move(start.x + 55, start.y + 35, { steps: 5 }); await host.page.mouse.up();
  await expect(comment).toBeFocused(); await comment.fill('Area feedback');
  await expect(panel.surface.locator('main')).toHaveAttribute('data-saved', 'true', { timeout: 20000 });
  graph = decodeDocument(await readFile(checkpointPath, 'utf8'));
  assert.equal(graph.canvyResources.annotations.length, 2); assert.equal(graph.canvyResources.annotations[1].target.kind, 'area');
  const areaId = graph.canvyResources.annotations[1].id;
  const pin = panel.surface.getByRole('button', { name: 'Annotation 2: Area feedback', exact: true });
  const pinBefore = await pin.boundingBox();
  const zoom = (await call('canvas_viewport_get', target)).zoom;
  const frame = await call('get_node', { ...target, id: frameId });
  await call('canvas_update_node', { ...target, id: frameId, x: frame.x + 30 });
  const pinAfter = await pin.boundingBox();
  assert.ok(Math.abs(pinAfter.x - pinBefore.x - 30 * zoom) < 2);
  await panel.surface.getByRole('button', { name: 'Close annotation' }).click();
  await host.page.mouse.move(canvasBox.x + 600, canvasBox.y + 700); await host.page.keyboard.down('Space');
  await host.page.mouse.down(); await host.page.mouse.move(canvasBox.x + 640, canvasBox.y + 720, { steps: 5 }); await host.page.mouse.up(); await host.page.keyboard.up('Space');
  assert.deepEqual([...(decodeDocument(await readFile(checkpointPath, 'utf8')).canvyResources.annotations)].map(a => a.id), [note.id, areaId]);
  checks.push('Area markers follow moved frame geometry and Space-drag pans in Annotate without changing feedback identity');
  await pin.click(); await panel.surface.getByRole('button', { name: 'Remove annotation' }).click();
  await expect(pin).toHaveCount(0); await panel.surface.getByRole('button', { name: 'Undo remove' }).click(); await expect(pin).toBeVisible();
  await panel.surface.getByRole('button', { name: 'Interact', exact: true }).click();
  await expect(item).toBeVisible(); await expect(prototype.getByText('Count: 0', { exact: true })).toBeVisible();
  const result = await call('canvas_import_react', { ...target, source: 'export default function Screen(){return <div>Undo fixture</div>}', viewports: [{ width: 300, height: 300 }], x: 800 });
  await panel.surface.getByRole('button', { name: 'Annotate', exact: true }).click(); await pin.click();
  await comment.fill('Feedback created after structural edit');
  await call('canvas_undo', target);
  graph = decodeDocument(await readFile(checkpointPath, 'utf8'));
  assert.ok(!graph.getNode(result.frames[0].id)); assert.equal(graph.canvyResources.annotations[1].text, 'Feedback created after structural edit');
  checks.push('Removal is reversible; Annotate preserves live React state across modes and design undo does not erase newer feedback');
  await call('switch_canvas', {}); await call('switch_canvas', target);
  await expect(panel.surface.getByRole('button', { name: 'Annotation 2: Feedback created after structural edit', exact: true })).toBeVisible();
  assert.equal((await call('send_selection_to_chat', target)).annotations[1].id, areaId);
  const another = (await call('create_canvas', { name: 'Separate annotations QA' })).document;
  await call('switch_canvas', { document_id: another.id });
  assert.equal(await panel.surface.locator('.annotation-pin').count(), 0);
  assert.ok(!('annotations' in (await call('send_selection_to_chat', { document_id: another.id }))));
  const native = await call('create_shape', { document_id: another.id, type: 'RECTANGLE', name: 'Native annotation target', x: 100, y: 100, width: 400, height: 200 });
  await call('canvas_viewport_zoom_to_fit', { document_id: another.id, ids: [native.id] });
  const nativeCanvas = await panel.surface.getByTestId('design-canvas').boundingBox();
  await host.page.mouse.click(nativeCanvas.x + nativeCanvas.width / 2, nativeCanvas.y + nativeCanvas.height / 2);
  await expect(comment).toBeVisible(); await comment.fill('Keep this native target editable');
  await expect(panel.surface.locator('main')).toHaveAttribute('data-saved', 'true');
  const nativeGraph = decodeDocument(await readFile(resolve(storage, 'canvases', another.id + '.freecanvas'), 'utf8'));
  assert.equal(nativeGraph.canvyResources.annotations[0].target.node_id, native.id);
  assert.equal(nativeGraph.canvyResources.annotations[0].target.source, 'native-design');
  checks.push('Native-only mockups can be annotated with stable node IDs without requiring a React prototype');
  assert.deepEqual(host.errors, []);
  checks.push('Checkpoint reload retains annotations and IDs; another canvas gets neither pins nor stale feedback context');
  await writeFile('artifacts/annotations-test.json', JSON.stringify({ status: 'PASS', host: 'OPAQUE MCP APPS PROTOCOL HARNESS, NOT ACTUAL CODEX DICTATION', checks }, null, 2));
  console.log(checks.map(c => 'PASS ' + c).join('\n'));
} finally { await host?.close(); await client.close(); if (service.exitCode === null) { const exited = once(service, 'exit'); service.kill(); await exited; } }
