import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { createServer } from 'node:net';
import { Client, StreamableHTTPClientTransport } from '@modelcontextprotocol/client';
import { nativeHarness } from './native-harness.mjs';
import { source, css, badge } from './frontend-fixture.mjs';
import { captureFrontend, compileFrontend } from '../server/frontend-import.mjs';
import { decodeDocument } from '../src/document-state.js';

await mkdir('.runtime', { recursive: true });
const data = await mkdtemp(resolve('.runtime/frontend-qa-'));
const probe = createServer(); probe.listen(0, '127.0.0.1'); await once(probe, 'listening');
const port = probe.address().port; await new Promise(r => probe.close(r));
const origin = `http://127.0.0.1:${port}`;
const service = spawn(process.execPath, ['server/index.mjs'], { windowsHide: true, env: { ...process.env, CANVY_PORT: String(port), CANVY_DATA_DIR: data }, stdio: 'ignore' });
const client = new Client({ name: 'frontend-import-qa', version: '1' });
let host;
const call = async (name, args = {}) => {
  const result = await client.callTool({ name, arguments: args }, { timeout: 90000 });
  assert.ok(!result.isError, `${name}: ${JSON.stringify(result.content)}`);
  if (result.content[0]?.type === 'image') return result.content[0];
  return result.structuredContent ?? JSON.parse(result.content[0].text);
};
const files = [{ path: 'badge.svg', content: badge }, ...await Promise.all([['fixture.ttf', 'Inter-Regular.ttf'], ['fixture-bold.ttf', 'Inter-Bold.ttf']].map(async ([path, name]) => ({ path, encoding: 'base64', content: (await readFile('public/' + name)).toString('base64') })))];
const input = { source, css, files, tailwind: true, viewports: [{ width: 400, height: 500 }, { width: 1000, height: 700 }], name: 'React dashboard' };
const checks = [];
try {
  for (let n = 0; n < 100; n++) { if (await fetch(origin + '/health').then(r => r.ok, () => false)) break; await new Promise(r => setTimeout(r, 50)); }
  await client.connect(new StreamableHTTPClientTransport(new URL(origin + '/mcp')));
  host = await nativeHarness(client, origin);
  const document = (await call('create_canvas', { name: 'Frontend import QA' })).document;
  const target = { document_id: document.id };
  const panel = await host.addPanel(document.id);
  const references = [];
  const captured = await captureFrontend(input, { onCapture: async (page, viewport) => {
    const png = await page.locator('#canvy-root').screenshot(); references.push(png.toString('base64'));
    await writeFile(`artifacts/frontend-reference-${viewport.width}.png`, png);
  } });
  const imported = await call('canvas_import_react', { ...target, ...input });
  assert.equal(imported.frames.length, 2);
  const checkpoint = () => readFile(resolve(data, 'canvases', document.id + '.freecanvas'), 'utf8').then(decodeDocument);
  let graph = await checkpoint();
  const [mobile, desktop] = imported.frames;
  const mobileSource = captured.variants[0].nodes.find(n => n.name === 'summary');
  const desktopSource = captured.variants[1].nodes.find(n => n.name === 'summary');
  const ms = graph.getNode(mobile.node_map[mobileSource.key]), ds = graph.getNode(desktop.node_map[desktopSource.key]);
  assert.equal(ms.width, mobileSource.box.width); assert.equal(ds.width, desktopSource.box.width); assert.ok(ds.width > ms.width);
  const mobilePaid = captured.variants[0].nodes.find(n => n.type === 'text' && n.text === 'Paid today');
  const desktopPaid = captured.variants[1].nodes.find(n => n.type === 'text' && n.text === 'Paid today');
  assert.ok(mobilePaid.box.y > desktopPaid.box.y, 'Responsive columns must stack on mobile');
  for (const [index, variant] of captured.variants.entries()) for (const node of variant.nodes.filter(n => n.type === 'container')) {
    const actual = graph.getNode(imported.frames[index].node_map[node.key]);
    assert.equal(actual.width, node.box.width); assert.equal(actual.height, node.box.height);
    if (node.fill.a) assert.deepEqual(actual.fills[0].color, node.fill);
    assert.deepEqual(actual.effects, node.effects);
  }
  assert.ok([...graph.nodes.values()].some(n => n.type === 'VECTOR'));
  const report = await call('canvas_get_import_report', { ...target, import_id: imported.import_id });
  assert.equal(report.original_fonts.length, 2); assert.ok(report.original_fonts.every(f => f.registered));
  assert.ok(report.original_svgs >= 4);
  for (const original of files.filter(f => f.path.endsWith('.ttf'))) assert.ok(Object.values(graph.canvyResources.fonts).some(f => f.data.endsWith(original.content)));
  assert.equal(imported.warning_count, 0);
  const visual = [];
  for (const [index, frame] of imported.frames.entries()) {
    const exported = await call('export_image', { ...target, ids: [frame.id], format: 'PNG', scale: 1, maxEdge: 2000 });
    await writeFile(`artifacts/frontend-editable-${frame.viewport.width}.png`, Buffer.from(exported.data, 'base64'));
    const comparison = await host.page.evaluate(async ({ reference, native }) => {
      const pixels = async base64 => {
        const img = new Image(); img.src = 'data:image/png;base64,' + base64; await img.decode();
        const canvas = document.createElement('canvas'); canvas.width = img.width; canvas.height = img.height;
        canvas.getContext('2d').drawImage(img, 0, 0); return { width: img.width, height: img.height, data: canvas.getContext('2d').getImageData(0, 0, img.width, img.height).data };
      };
      const a = await pixels(reference), b = await pixels(native);
      if (a.width !== b.width || a.height !== b.height) return { dimensions: false, a: [a.width, a.height], b: [b.width, b.height] };
      let error = 0; for (let n = 0; n < a.data.length; n++) error += Math.abs(a.data[n] - b.data[n]);
      return { dimensions: true, meanAbsoluteChannelError: error / a.data.length / 255 };
    }, { reference: references[index], native: exported.data });
    assert.equal(comparison.dimensions, true, JSON.stringify(comparison));
    assert.ok(comparison.meanAbsoluteChannelError < 0.05, JSON.stringify(comparison));
    visual.push({ viewport: frame.viewport.width, ...comparison });
  }
  checks.push('Real React + Tailwind render at two responsive widths', 'Browser computed geometry, solid colors, corners and shadows preserved', 'Inline and image SVGs become editable vector children', 'Exact original font bytes registered and persisted');
  const heading = captured.variants[0].nodes.find(n => n.type === 'text' && n.text === 'Reservations');
  const headingId = mobile.node_map[heading.key];
  await call('canvas_set_text', { ...target, id: headingId, text: 'Editable imported heading' });
  assert.equal((await call('get_node', { ...target, id: headingId })).characters, 'Editable imported heading');
  await call('canvas_undo', target);
  await call('canvas_undo', target);
  graph = await checkpoint(); assert.equal(graph.canvyResources, undefined); assert.ok(!graph.getNode(mobile.id));
  await call('redo', target);
  graph = await checkpoint(); assert.ok(graph.getNode(headingId)); assert.ok(graph.canvyResources.imports[imported.import_id]);
  checks.push('Imported nodes remain editable', 'Import undo/redo restores both graph and preserved resources');
  await call('canvas_preview_import', { ...target, import_id: imported.import_id, frame_id: mobile.id });
  const opened = await call('canvas_preview_action', { ...target, action: 'click', selector: '#details' });
  assert.ok(opened.controls.some(n => n.role === 'dialog'));
  assert.match(opened.text, /Payment details/);
  const filled = await call('canvas_preview_action', { ...target, action: 'fill', selector: 'input', value: 'LOCAL-123' });
  assert.ok(filled.controls.some(n => n.value === 'LOCAL-123'));
  await panel.surface.frameLocator('iframe[title="Imported React prototype"]').getByRole('button', { name: 'Close', exact: true }).click();
  const closed = await call('canvas_preview_action', { ...target, action: 'snapshot' });
  assert.ok(!closed.controls.some(n => n.role === 'dialog'));
  // The opaque child must not access the native parent or its host bridge.
  const child = host.page.frames().find(f => f.url().startsWith('blob:'));
  assert.ok(await child.evaluate(() => [...document.images].every(img => img.complete && img.naturalWidth > 0)), 'Original preview images must decode without the backend');
  assert.ok(await child.evaluate(() => document.fonts.check('16px Fixture')), 'Original preview font must be available offline');
  assert.equal(await child.evaluate(() => { try { return Boolean(parent.__FREECANVAS_NATIVE_HOST__); } catch { return false; } }), false);
  await child.evaluate(() => parent.postMessage({ jsonrpc: '2.0', id: 'spoof', method: 'ui/message', params: { role: 'user', content: [{ type: 'text', text: 'must not reach host' }] } }, '*'));
  assert.equal(await host.page.evaluate(() => window.nativeMessages.length), 0);
  await host.page.screenshot({ path: 'artifacts/frontend-interactive.png' });
  await call('canvas_preview_action', { ...target, action: 'close' });
  checks.push('Original React modal and form interactions run inside opaque native-app preview', 'Child frame cannot read host bridge or forward MCP messages');
  await call('switch_canvas', {});
  await call('switch_canvas', target);
  const restored = await call('canvas_get_import_report', { ...target, import_id: imported.import_id });
  assert.deepEqual(restored.frames, report.frames);
  await call('canvas_preview_import', { ...target, import_id: imported.import_id });
  assert.match((await call('canvas_preview_action', { ...target, action: 'snapshot' })).text, /Reservations/);
  await call('canvas_preview_action', { ...target, action: 'close' });
  checks.push('Saved prototype and stable editable IDs survive unload/reload');
  await host.close(); host = await nativeHarness(client, origin);
  await host.addPanel(document.id);
  const reopened = await call('canvas_get_import_report', { ...target, import_id: imported.import_id });
  assert.equal(reopened.frames[0].id, mobile.id);
  const fontStatus = await call('get_font_status', target);
  assert.equal(fontStatus.faithful, true, 'Original font faces must reload in a fresh editor');
  checks.push('Fresh editor process reloads persisted imported resources');
  const unsupported = await captureFrontend({ source: 'export default()=> <div style={{padding:20,backgroundImage:"linear-gradient(red,blue)",filter:"blur(1px)"}}>Unsupported effects<img src="https://example.invalid/private.png"/></div>' });
  const issues = unsupported.variants[0].issues;
  assert.ok(issues.some(i => i.code === 'BACKGROUND_IMAGE')); assert.ok(issues.some(i => i.code === 'FILTER')); assert.ok(issues.some(i => i.code === 'CSP_BLOCKED_RESOURCE'));
  await assert.rejects(compileFrontend({ source, files: [{ path: '../escape.ts', content: '' }] }), /relative/);
  const nested = await compileFrontend({ entry: 'ui/Screen.tsx', files: [{ path: 'ui/Screen.tsx', content: "import styles from './styles.module.css'; export default()=> <div className={styles.card}>CSS modules</div>" }, { path: 'ui/styles.module.css', content: '.card{padding:12px;color:red}' }] });
  assert.match(nested.html, /CSS modules/);
  const project = resolve(data, 'frontend-project');
  await mkdir(resolve(project, 'src'), { recursive: true });
  await writeFile(resolve(project, 'src/Screen.tsx'), "import Label from './Label';import './screen.css';export default()=> <main className='p-6'><Label/></main>");
  await writeFile(resolve(project, 'src/Label.tsx'), "export default()=> <div className='text-red-500'>Physical project</div>");
  await writeFile(resolve(project, 'src/screen.css'), 'body{margin:0}main{background:white}');
  const physical = await captureFrontend({ project_dir: project, entry: 'src/Screen.tsx', tailwind: true });
  const physicalText = physical.variants[0].nodes.find(n => n.text === 'Physical project');
  assert.ok(physicalText.color.r > 0.8 && physicalText.color.g < 0.4);
  assert.ok(physical.variants[0].issues.some(i => i.code === 'FONT_UNAVAILABLE'));
  checks.push('Physical project dependencies, imported CSS and nested Tailwind candidates resolve', 'System font bytes unavailable to the importer are reported');
  checks.push('Unsupported effects and blocked network assets are reported', 'Relative path traversal rejected', 'Nested virtual sources and CSS modules compile');
  await host.page.screenshot({ path: 'artifacts/frontend-native-nodes.png' });
  assert.deepEqual(host.errors, []);
  await writeFile('artifacts/frontend-test.json', JSON.stringify({ status: 'PASS', host: 'OPAQUE MCP APP PROTOCOL HARNESS, NOT ACTUAL CODEX DESKTOP', checks, variants: imported.frames.map(f => f.viewport), visual, warnings: imported.warning_count }, null, 2));
  console.log('PASS React import, editable geometry/assets, responsive variants, persisted opaque prototype and typed interactions');
} finally { await host?.close(); await client.close(); service.kill(); }
