import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { createServer } from 'node:net';
import { Client, StreamableHTTPClientTransport } from '@modelcontextprotocol/client';
import { nativeHarness } from './native-harness.mjs';
import { waitForService } from './service-ready.mjs';
import { source, css, badge } from './frontend-fixture.mjs';
import { source as effectsSource, css as effectsCss } from './frontend-effects-fixture.mjs';
import { captureFrontend, compileFrontend } from '../server/frontend-import.mjs';
import { decodeDocument } from '../src/document-state.js';
import { parseFigBuffer } from '@open-pencil/fig';

await mkdir('.runtime', { recursive: true });
const data = await mkdtemp(resolve('.runtime/frontend-qa-'));
const probe = createServer(); probe.listen(0, '127.0.0.1'); await once(probe, 'listening');
const port = probe.address().port; await new Promise(r => probe.close(r));
const origin = `http://127.0.0.1:${port}`;
const service = spawn(process.execPath, ['server/index.mjs'], { windowsHide: true, env: { ...process.env, CANVY_PORT: String(port), CANVY_DATA_DIR: data }, stdio: 'ignore' });
const client = new Client({ name: 'frontend-import-qa', version: '1' });
let host;
const call = async (name, args = {}) => {
  const result = await client.callTool({ name, arguments: args }, { timeout: 90000 });
  assert.ok(!result.isError, `${name}: ${JSON.stringify(result.content)}`);
  if (result.content[0]?.type === 'image') return result.content[0];
  return result.structuredContent ?? JSON.parse(result.content[0].text);
};
const files = [{ path: 'badge.svg', content: badge }, ...await Promise.all([['fixture.ttf', 'Inter-Regular.ttf'], ['fixture-bold.ttf', 'Inter-Bold.ttf']].map(async ([path, name]) => ({ path, encoding: 'base64', content: (await readFile('public/' + name)).toString('base64') })))];
const input = { source, css, files, tailwind: true, viewports: [{ width: 400, height: 500 }, { width: 1000, height: 700 }], name: 'React dashboard' };
const checks = [];
try {
  await waitForService(origin, service);
  await client.connect(new StreamableHTTPClientTransport(new URL(origin + '/mcp')));
  host = await nativeHarness(client, origin, undefined, { nonceCsp: true });
  const document = (await call('create_canvas', { name: 'Frontend import QA' })).document;
  const target = { document_id: document.id };
  const panel = await host.addPanel(document.id, { collapsed: true });
  assert.equal(await panel.surface.getByTestId('design-canvas').evaluate(e => e.clientWidth), 0);
  assert.deepEqual(await panel.surface.getByTestId('design-canvas').evaluate(e => ({ width: e.width, height: e.height, ready: e.dataset.ready })), { width: 800, height: 600, ready: '1' });
  checks.push('Collapsed zero-size native app initializes and attaches without RAF');
  const references = [];
  const captured = await captureFrontend(input, { onCapture: async (page, viewport) => {
    const png = await page.screenshot(); references.push(png.toString('base64'));
    await writeFile(`artifacts/frontend-reference-${viewport.width}.png`, png);
  } });
  const imported = await call('canvas_import_react', { ...target, ...input });
  assert.equal(imported.frames.length, 2);
  const checkpoint = () => readFile(resolve(data, 'canvases', document.id + '.freecanvas'), 'utf8').then(decodeDocument);
  let graph = await checkpoint();
  const [mobile, desktop] = imported.frames;
  for (const [index, frame] of imported.frames.entries()) {
    assert.equal(graph.getNode(frame.id).width, input.viewports[index].width);
    assert.equal(graph.getNode(frame.id).height, input.viewports[index].height);
  }
  const mobileSource = captured.variants[0].nodes.find(n => n.name === 'summary');
  const desktopSource = captured.variants[1].nodes.find(n => n.name === 'summary');
  const ms = graph.getNode(mobile.node_map[mobileSource.key]), ds = graph.getNode(desktop.node_map[desktopSource.key]);
  assert.equal(ms.width, mobileSource.box.width); assert.equal(ds.width, desktopSource.box.width); assert.ok(ds.width > ms.width);
  const mobilePaid = captured.variants[0].nodes.find(n => n.type === 'text' && n.text === 'Paid today');
  const desktopPaid = captured.variants[1].nodes.find(n => n.type === 'text' && n.text === 'Paid today');
  assert.ok(mobilePaid.box.y > desktopPaid.box.y, 'Responsive columns must stack on mobile');
  for (const [index, variant] of captured.variants.entries()) for (const node of variant.nodes.filter(n => n.type === 'container')) {
    const actual = graph.getNode(imported.frames[index].node_map[node.key]);
    assert.equal(actual.width, node.box.width); assert.equal(actual.height, node.box.height);
    if (node.fill.a) assert.deepEqual(actual.fills[0].color, node.fill);
    assert.deepEqual(actual.effects, node.effects);
  }
  assert.ok([...graph.nodes.values()].some(n => n.type === 'VECTOR'));
  const report = await call('canvas_get_import_report', { ...target, import_id: imported.import_id });
  assert.equal(report.original_fonts.length, 2); assert.ok(report.original_fonts.every(f => f.registered));
  assert.ok(report.original_svgs >= 4);
  for (const original of files.filter(f => f.path.endsWith('.ttf'))) assert.ok(Object.values(graph.canvyResources.fonts).some(f => f.data.endsWith(original.content)));
  assert.equal(imported.warning_count, 0);
  const visual = [];
  for (const [index, frame] of imported.frames.entries()) {
    const exported = await call('export_image', { ...target, ids: [frame.id], format: 'PNG', scale: 1, maxEdge: 2000 });
    await writeFile(`artifacts/frontend-editable-${frame.viewport.width}.png`, Buffer.from(exported.data, 'base64'));
    const comparison = await host.page.evaluate(async ({ reference, native }) => {
      const pixels = async base64 => {
        const img = new Image(); const url = URL.createObjectURL(new Blob([Uint8Array.from(atob(base64), c => c.charCodeAt(0))], { type: 'image/png' })); img.src = url; await img.decode(); URL.revokeObjectURL(url);
        const canvas = document.createElement('canvas'); canvas.width = img.width; canvas.height = img.height;
        canvas.getContext('2d').drawImage(img, 0, 0); return { width: img.width, height: img.height, data: canvas.getContext('2d').getImageData(0, 0, img.width, img.height).data };
      };
      const a = await pixels(reference), b = await pixels(native);
      if (a.width !== b.width || a.height !== b.height) return { dimensions: false, a: [a.width, a.height], b: [b.width, b.height] };
      let error = 0; for (let n = 0; n < a.data.length; n++) error += Math.abs(a.data[n] - b.data[n]);
      return { dimensions: true, meanAbsoluteChannelError: error / a.data.length / 255 };
    }, { reference: references[index], native: exported.data });
    assert.equal(comparison.dimensions, true, JSON.stringify(comparison));
    assert.ok(comparison.meanAbsoluteChannelError < 0.05, JSON.stringify(comparison));
    visual.push({ viewport: frame.viewport.width, ...comparison });
  }
  checks.push('Real React + Tailwind render at two responsive widths', 'Browser computed geometry, solid colors, corners and shadows preserved', 'Inline and image SVGs become editable vector children', 'Exact original font bytes registered and persisted');
  const heading = captured.variants[0].nodes.find(n => n.type === 'text' && n.text === 'Reservations');
  const headingId = mobile.node_map[heading.key];
  await call('canvas_set_text', { ...target, id: headingId, text: 'Editable imported heading' });
  assert.equal((await call('get_node', { ...target, id: headingId })).characters, 'Editable imported heading');
  await call('canvas_undo', target);
  await call('canvas_undo', target);
  graph = await checkpoint(); assert.equal(graph.canvyResources, undefined); assert.ok(!graph.getNode(mobile.id));
  await call('redo', target);
  graph = await checkpoint(); assert.ok(graph.getNode(headingId)); assert.ok(graph.canvyResources.imports[imported.import_id]);
  checks.push('Imported nodes remain editable', 'Import undo/redo restores both graph and preserved resources');
  await call('canvas_preview_import', { ...target, import_id: imported.import_id, frame_id: mobile.id });
  const opened = await call('canvas_preview_action', { ...target, action: 'click', selector: '#details' });
  assert.ok(opened.controls.some(n => n.role === 'dialog'));
  assert.match(opened.text, /Payment details/);
  const filled = await call('canvas_preview_action', { ...target, action: 'fill', selector: 'input', value: 'LOCAL-123' });
  assert.ok(filled.controls.some(n => n.value === 'LOCAL-123'));
  checks.push('Import, export, autosave and React actions succeed in a collapsed panel');
  await host.page.locator('#' + panel.id).evaluate(e => { e.style.width = '100%'; e.style.height = '100%'; });
  await panel.surface.getByTestId('design-canvas').evaluate(async e => {
    const deadline = Date.now() + 5000;
    while (e.width !== e.clientWidth * devicePixelRatio && Date.now() < deadline) await new Promise(r => setTimeout(r, 25));
  });
  assert.equal(await panel.surface.getByTestId('design-canvas').evaluate(e => e.width), 1200);
  await panel.surface.frameLocator('iframe[title="Imported React prototype"]').getByRole('button', { name: 'Close', exact: true }).click();
  const closed = await call('canvas_preview_action', { ...target, action: 'snapshot' });
  assert.ok(!closed.controls.some(n => n.role === 'dialog'));
  // The opaque child must not access the native parent or its host bridge.
  const child = await (await panel.surface.locator('iframe[title="Imported React prototype"]').elementHandle()).contentFrame();
  assert.ok(await child.evaluate(() => [...document.images].every(img => img.complete && img.naturalWidth > 0)), 'Original preview images must decode without the backend');
  assert.ok(await child.evaluate(() => document.fonts.check('16px Fixture')), 'Original preview font must be available offline');
  assert.equal(await child.evaluate(() => { try { return Boolean(parent.__FREECANVAS_NATIVE_HOST__); } catch { return false; } }), false);
  await child.evaluate(() => parent.postMessage({ jsonrpc: '2.0', id: 'spoof', method: 'ui/message', params: { role: 'user', content: [{ type: 'text', text: 'must not reach host' }] } }, '*'));
  assert.equal(await host.page.evaluate(() => window.nativeMessages.length), 0);
  await host.page.screenshot({ path: 'artifacts/frontend-interactive.png' });
  await call('canvas_preview_action', { ...target, action: 'close' });
  checks.push('Original React modal and form interactions run inside opaque native-app preview', 'Child frame cannot read host bridge or forward MCP messages');
  checks.push('Inherited nonce-only script CSP permits the bundled prototype');
  checks.push('Expanded host viewport replaces the collapsed backing-buffer dimensions');
  await call('switch_canvas', {});
  await call('switch_canvas', target);
  const restored = await call('canvas_get_import_report', { ...target, import_id: imported.import_id });
  assert.deepEqual(restored.frames, report.frames);
  await call('canvas_preview_import', { ...target, import_id: imported.import_id });
  assert.match((await call('canvas_preview_action', { ...target, action: 'snapshot' })).text, /Reservations/);
  await call('canvas_preview_action', { ...target, action: 'close' });
  checks.push('Saved prototype and stable editable IDs survive unload/reload');
  await host.close(); host = await nativeHarness(client, origin, undefined, { nonceCsp: true });
  await host.addPanel(document.id);
  const reopened = await call('canvas_get_import_report', { ...target, import_id: imported.import_id });
  assert.equal(reopened.frames[0].id, mobile.id);
  const fontStatus = await call('get_font_status', target);
  assert.equal(fontStatus.faithful, true, 'Original font faces must reload in a fresh editor');
  checks.push('Fresh editor process reloads persisted imported resources');
  const effectsInput = { source: effectsSource, css: effectsCss, files, viewports: [{ width: 400, height: 800 }], name: 'Browser effects' };
  let effectsReference;
  const effectCapture = await captureFrontend(effectsInput, { onCapture: async page => {
    effectsReference = (await page.screenshot()).toString('base64');
    await writeFile('artifacts/frontend-effects-reference.png', Buffer.from(effectsReference, 'base64'));
  } });
  const effectImport = await call('canvas_import_react', { ...target, ...effectsInput });
  const effectFrame = effectImport.frames[0], effectNodes = effectCapture.variants[0].nodes;
  graph = await checkpoint();
  const fig = await readFile(resolve(data, 'canvases', document.id + '.fig'));
  const figPayload = parseFigBuffer(fig.buffer.slice(fig.byteOffset, fig.byteOffset + fig.byteLength));
  assert.ok(figPayload.nodeChanges.some(n => n.fillPaints?.some(p => p.imageScaleMode === 'STRETCH' && p.transform)), 'Transformed image fills must serialize as valid interoperable .fig paints');
  assert.ok(graph.getNode(effectFrame.node_map[effectNodes.find(n => n.name === 'gradient').key]).fills.some(f => f.type === 'GRADIENT_LINEAR'));
  assert.ok(effectNodes.filter(n => n.type === 'text' && n.parent === effectNodes.find(n => n.name === 'wrapped').key).length >= 3);
  const pattern = graph.getNode(effectFrame.node_map[effectNodes.find(n => n.name === 'pattern').key]);
  assert.ok(pattern.childIds.some(id => graph.getNode(id).fills.some(f => f.type === 'IMAGE')));
  assert.ok(pattern.childIds.some(id => graph.getNode(id).type === 'TEXT' && graph.getNode(id).visible));
  const rotated = graph.getNode(effectFrame.node_map[effectNodes.find(n => n.name === 'rotated').key]);
  assert.ok(rotated.childIds.some(id => graph.getNode(id).type === 'TEXT' && !graph.getNode(id).visible));
  const emojiSource = effectNodes.find(n => n.name === 'emoji-avatar');
  const emoji = graph.getNode(effectFrame.node_map[emojiSource.key]);
  assert.equal(emojiSource.raster.mode, 'composite');
  assert.ok(emoji.childIds.some(id => graph.getNode(id).fills.some(f => f.type === 'IMAGE')));
  assert.ok(emoji.childIds.some(id => graph.getNode(id).text === '👨🏼‍✈️' && !graph.getNode(id).visible));
  assert.ok(effectFrame.visual_layers.some(n => /Emoji font fallback/.test(n.reason)));
  const overlap = graph.getNode(effectFrame.node_map[effectNodes.find(n => n.name === 'overlap').key]);
  assert.deepEqual(overlap.childIds.map(id => graph.getNode(id).name), ['below', 'above']);
  assert.ok(effectFrame.visual_layers.some(n => n.mode === 'decoration'));
  assert.ok(effectFrame.visual_layers.some(n => n.mode === 'composite'));
  const effectExport = await call('export_image', { ...target, ids: [effectFrame.id], format: 'PNG', scale: 1, maxEdge: 2000 });
  await writeFile('artifacts/frontend-effects-editable.png', Buffer.from(effectExport.data, 'base64'));
  const effectsVisual = await host.page.evaluate(async ({ a, b }) => {
    const pixels = async data => { const img = new Image(); const url = URL.createObjectURL(new Blob([Uint8Array.from(atob(data), c => c.charCodeAt(0))], { type: 'image/png' })); img.src = url; await img.decode(); URL.revokeObjectURL(url); const c = document.createElement('canvas'); c.width = img.width; c.height = img.height; c.getContext('2d').drawImage(img, 0, 0); return { w: c.width, h: c.height, data: c.getContext('2d').getImageData(0, 0, c.width, c.height).data }; };
    const source = await pixels(a), native = await pixels(b); let error = 0;
    if (source.w !== native.w || source.h !== native.h) return { dimensions: false, source: [source.w, source.h], native: [native.w, native.h] };
    for (let i = 0; i < source.data.length; i++) error += Math.abs(source.data[i] - native.data[i]);
    return { dimensions: true, meanAbsoluteChannelError: error / source.data.length / 255 };
  }, { a: effectsReference, b: effectExport.data });
  assert.equal(effectsVisual.dimensions, true, JSON.stringify(effectsVisual));
  assert.ok(effectsVisual.meanAbsoluteChannelError < 0.035, JSON.stringify(effectsVisual));
  const emojiVisual = await host.page.evaluate(async ({ a, b, box }) => {
    const pixels = async data => {
      const image = new Image(); const url = URL.createObjectURL(new Blob([Uint8Array.from(atob(data), c => c.charCodeAt(0))], { type: 'image/png' }));
      image.src = url; await image.decode(); URL.revokeObjectURL(url);
      const c = document.createElement('canvas'); c.width = image.width; c.height = image.height; c.getContext('2d').drawImage(image, 0, 0);
      return c.getContext('2d').getImageData(box.x, box.y, box.width, box.height).data;
    };
    const source = await pixels(a), native = await pixels(b); let error = 0;
    for (let i = 0; i < source.length; i++) error += Math.abs(source[i] - native[i]);
    return error / source.length / 255;
  }, { a: effectsReference, b: effectExport.data, box: emojiSource.box });
  assert.ok(emojiVisual < 0.02, `Emoji avatar pixel mismatch: ${emojiVisual}`);
  const patternText = effectNodes.find(n => n.text === 'Original background image');
  await call('canvas_set_text', { ...target, id: effectFrame.node_map[patternText.key], text: 'Editable over decoration' });
  await call('switch_canvas', {}); await call('switch_canvas', target);
  const effectsReport = await call('canvas_get_import_report', { ...target, import_id: effectImport.import_id });
  assert.deepEqual(effectsReport.frames[0].visual_layers, effectFrame.visual_layers);
  checks.push('Native gradients, editable browser line fragments and sibling stacking order', 'Background images, generated content, form chrome, transformed subtrees and complex SVGs retain disclosed visual layers', 'Emoji avatars preserve the browser visual, original text and explicit fallback report', 'Editable text over raster decorations and visual-layer reports survive autosave and reload');
  const unsupported = await captureFrontend({ source: 'export default()=> <div style={{padding:20,backgroundImage:"linear-gradient(red,blue)",filter:"blur(1px)"}}>Unsupported effects<img src="https://example.invalid/private.png"/></div>' });
  const issues = unsupported.variants[0].issues;
  assert.ok(unsupported.variants[0].nodes.some(n => n.backgroundPaint?.type === 'GRADIENT_LINEAR'));
  assert.ok(unsupported.variants[0].nodes.some(n => n.effects.some(e => e.type === 'LAYER_BLUR')));
  assert.ok(issues.some(i => i.code === 'CSP_BLOCKED_RESOURCE'));
  await assert.rejects(compileFrontend({ source, files: [{ path: '../escape.ts', content: '' }] }), /relative/);
  const nested = await compileFrontend({ entry: 'ui/Screen.tsx', files: [{ path: 'ui/Screen.tsx', content: "import styles from './styles.module.css'; export default()=> <div className={styles.card}>CSS modules</div>" }, { path: 'ui/styles.module.css', content: '.card{padding:12px;color:red}' }] });
  assert.match(nested.html, /CSS modules/);
  const overflowInput = { source: 'export default()=> <main style={{height:80,position:"relative"}}>Screen<span style={{position:"absolute",left:450,visibility:"hidden"}}>Hidden tooltip</span></main>', viewports: [{ width: 400, height: 500 }] };
  const overflow = await captureFrontend(overflowInput);
  assert.deepEqual([overflow.variants[0].width, overflow.variants[0].height], [400, 500]);
  const component = await captureFrontend({ ...overflowInput, selector: 'main' });
  assert.deepEqual([component.variants[0].width, component.variants[0].height], [400, 80]);
  checks.push('Screen frames match requested viewport sizes; hidden overflow cannot expand exports', 'Explicit component selectors preserve their visible border box');
  const project = resolve(data, 'frontend-project');
  await mkdir(resolve(project, 'src'), { recursive: true });
  await writeFile(resolve(project, 'src/Screen.tsx'), "import Label from './Label';import './screen.css';export default()=> <main className='p-6'><Label/></main>");
  await writeFile(resolve(project, 'src/Label.tsx'), "export default()=> <div className='text-red-500'>Physical project</div>");
  await writeFile(resolve(project, 'src/screen.css'), 'body{margin:0}main{background:white}');
  const physical = await captureFrontend({ project_dir: project, entry: 'src/Screen.tsx', tailwind: true });
  const physicalText = physical.variants[0].nodes.find(n => n.text === 'Physical project');
  assert.ok(physicalText.color.r > 0.8 && physicalText.color.g < 0.4);
  assert.ok(physical.variants[0].issues.some(i => i.code === 'FONT_UNAVAILABLE'));
  checks.push('Physical project dependencies, imported CSS and nested Tailwind candidates resolve', 'System font bytes unavailable to the importer are reported');
  checks.push('Unsupported effects and blocked network assets are reported', 'Relative path traversal rejected', 'Nested virtual sources and CSS modules compile');
  await host.page.screenshot({ path: 'artifacts/frontend-native-nodes.png' });
  assert.deepEqual(host.errors, []);
  await writeFile('artifacts/frontend-test.json', JSON.stringify({ status: 'PASS', host: 'OPAQUE MCP APP PROTOCOL HARNESS, NOT ACTUAL CODEX DESKTOP', checks, variants: imported.frames.map(f => f.viewport), visual, effectsVisual, warnings: imported.warning_count }, null, 2));
  console.log('PASS React import, editable geometry/assets, responsive variants, persisted opaque prototype and typed interactions');
} finally { await host?.close(); await client.close(); service.kill(); }
